/**
 * Copyright (c) 2026 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author Ludovic Autin <autin@scripps.edu>
 */

import { Segmentation } from '../../../../mol-data/int';
import { Mat4 } from '../../../../mol-math/linear-algebra';
import { CifWriter } from '../../../../mol-io/writer/cif';
import { StructureElement, StructureProperties as P } from '../../structure';
import { Unit } from '../../structure/unit';
import { CifExportContext } from '../mmcif';

import CifCategory = CifWriter.Category

export type InstanceAssemblyData = {
    /** One operator is written per transform; they map the exported coordinates onto each instance. */
    transforms: Mat4[],
    assemblyId?: string,
    details?: string
}

/**
 * `atom_site` holds a single copy of the model, so every transform becomes an operator that
 * generates one instance from it. No identity operator is implied: if a caller wants a copy left
 * in place, the identity has to be part of `transforms`.
 */
export function instanceAssemblyCategories(data: InstanceAssemblyData): CifCategory<CifExportContext>[] {
    const assemblyId = data.assemblyId || '1';
    const details = data.details || 'instance assembly generated by Mol*';

    return [
        {
            name: 'pdbx_struct_assembly',
            instance() {
                const rows: AssemblyRow[] = [{ id: assemblyId, details, count: data.transforms.length }];
                return { fields: AssemblyFields, source: [{ data: rows, rowCount: rows.length }] };
            }
        },
        {
            name: 'pdbx_struct_assembly_gen',
            instance(ctx) {
                const asymIds = getAsymIds(ctx);
                if (asymIds.length === 0 || data.transforms.length === 0) return CifCategory.Empty;
                const rows: AssemblyGenRow[] = [{
                    assembly_id: assemblyId,
                    oper_expression: getOperExpression(data.transforms.length),
                    asym_id_list: asymIds.join(',')
                }];
                return { fields: AssemblyGenFields, source: [{ data: rows, rowCount: rows.length }] };
            }
        },
        {
            name: 'pdbx_struct_oper_list',
            instance() {
                if (data.transforms.length === 0) return CifCategory.Empty;
                return { fields: OperListFields, source: [{ data: data.transforms, rowCount: data.transforms.length }] };
            }
        }
    ];
}

/** `1-N`, which `parseOperatorList` expands back into the individual ids. */
function getOperExpression(count: number) {
    return count === 1 ? '1' : `1-${count}`;
}

/** `label_asym_id`s of the exported coordinates, i.e. the chains the operators apply to. */
function getAsymIds(ctx: CifExportContext) {
    const seen = new Set<string>();
    const asymIds: string[] = [];

    for (const s of ctx.structures) {
        const l = StructureElement.Location.create(s);
        for (const unit of s.units) {
            if (unit.kind !== Unit.Kind.Atomic) continue;
            l.unit = unit;

            const { elements } = unit;
            const chainsIt = Segmentation.transientSegments(unit.model.atomicHierarchy.chainAtomSegments, elements);
            while (chainsIt.hasNext) {
                l.element = elements[chainsIt.move().start];
                const asymId = P.chain.label_asym_id(l);
                if (seen.has(asymId)) continue;
                seen.add(asymId);
                asymIds.push(asymId);
            }
        }
    }

    return asymIds;
}

type AssemblyRow = { id: string, details: string, count: number }
type AssemblyGenRow = { assembly_id: string, oper_expression: string, asym_id_list: string }

const AssemblyFields = CifWriter.fields<number, AssemblyRow[]>()
    .str('id', (i, xs) => xs[i].id)
    .str('details', (i, xs) => xs[i].details)
    .int('oligomeric_count', (i, xs) => xs[i].count)
    .getFields();

const AssemblyGenFields = CifWriter.fields<number, AssemblyGenRow[]>()
    .str('assembly_id', (i, xs) => xs[i].assembly_id)
    .str('oper_expression', (i, xs) => xs[i].oper_expression)
    .str('asym_id_list', (i, xs) => xs[i].asym_id_list)
    .getFields();

function operListFields() {
    const fields = CifWriter.fields<number, Mat4[]>()
        .int('id', (i) => i + 1)
        // enumerated by the mmCIF dictionary, so stick to the standard values
        .str('type', (i, xs) => Mat4.isIdentity(xs[i]) ? 'identity operation' : 'point symmetry operation')
        .str('name', (i) => `instance-${i + 1}`);

    // mmCIF is row-major and 1-indexed, Mat4 is column-major; Mat4.getValue(m, row, col) bridges the two
    for (let row = 0; row < 3; ++row) {
        for (let col = 0; col < 3; ++col) {
            fields.float(`matrix[${row + 1}][${col + 1}]`, (i, xs) => Mat4.getValue(xs[i], row, col), { digitCount: 6 });
        }
    }
    for (let row = 0; row < 3; ++row) {
        fields.float(`vector[${row + 1}]`, (i, xs) => Mat4.getValue(xs[i], row, 3), { digitCount: 6 });
    }

    return fields.getFields();
}

const OperListFields = operListFields();
