/**
 * Copyright (c) 2026 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author OpenAI
 */

import { AnimationProps } from '../../mol-geo/geometry/animation';
import { AudioReactiveAnimationManagerValues } from '../manager/audio-reactive-animation';

export type AudioReactivePresetName =
    | 'punchy-drums'
    | 'bass-groove'
    | 'bass-groove-strong'
    | 'bass-spectrum'
    | 'ambient-pulse'
    | 'performance'
    | 'full-spectrum';

export type AudioReactivePresetDefinition = {
    name: AudioReactivePresetName,
    label: string,
    description: string,
    analysis: Partial<AudioReactiveAnimationManagerValues>,
    animation: Partial<AnimationProps>,
};

export const AudioReactivePresetDefinitions: readonly AudioReactivePresetDefinition[] = [
    {
        name: 'punchy-drums',
        label: 'Punchy Drums',
        description: 'Strong beat-driven translation with fast onset and medium decay.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 1024,
            analysisSampleRate: 24000,
            bandNormalizationGain: 12,
            amplitudeAttackMs: 8,
            amplitudeReleaseMs: 120,
            bandAttackMs: 8,
            bandReleaseMs: 180,
            beatAttackMs: 0,
            beatReleaseMs: 240,
            dominantFrequencyAttackMs: 8,
            dominantFrequencyReleaseMs: 120,
            beatThreshold: 1.08,
            beatSensitivity: 16,
            beatBaselineMs: 180,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 7,
            wiggleAmplitude: 0.45,
            wiggleFrequency: 0.2,
            tumbleSpeed: 1.2,
            tumbleAmplitude: 8,
            tumbleFrequency: 0.2,
            audioWiggleSource: 'highMids',
            audioWiggleStrength: 0.8,
            audioWiggleFloor: 0,
            audioTumbleSource: 'beat',
            audioTumbleStrength: 2.6,
            audioTumbleFloor: 0,
        }
    },
    {
        name: 'bass-groove',
        label: 'Bass Groove',
        description: 'Sustained low-end motion with smoother translation.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 2048,
            analysisSampleRate: 24000,
            bandNormalizationGain: 10,
            amplitudeAttackMs: 12,
            amplitudeReleaseMs: 180,
            bandAttackMs: 20,
            bandReleaseMs: 280,
            beatAttackMs: 0,
            beatReleaseMs: 180,
            dominantFrequencyAttackMs: 12,
            dominantFrequencyReleaseMs: 160,
            beatThreshold: 1.18,
            beatSensitivity: 10,
            beatBaselineMs: 240,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 6,
            wiggleAmplitude: 0.35,
            wiggleFrequency: 0.18,
            tumbleSpeed: 1.0,
            tumbleAmplitude: 6,
            tumbleFrequency: 0.18,
            tumbleTranslationMode: 'axis',
            tumbleAxisSource: 'assembly',
            tumbleAxis: 'z',
            audioWiggleSource: 'lowMids',
            audioWiggleStrength: 0.7,
            audioWiggleFloor: 0.05,
            audioTumbleSource: 'bass',
            audioTumbleStrength: 2.2,
            audioTumbleFloor: 0.08,
        }
    },
    {
        name: 'bass-groove-strong',
        label: 'Bass Groove Strong',
        description: 'Stronger low-end translation with a bit more visual weight.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 1024,
            analysisSampleRate: 24000,
            bandNormalizationGain: 12,
            amplitudeAttackMs: 10,
            amplitudeReleaseMs: 170,
            bandAttackMs: 14,
            bandReleaseMs: 240,
            beatAttackMs: 0,
            beatReleaseMs: 180,
            dominantFrequencyAttackMs: 10,
            dominantFrequencyReleaseMs: 140,
            beatThreshold: 1.12,
            beatSensitivity: 12,
            beatBaselineMs: 220,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 5.5,
            wiggleAmplitude: 0.2,
            wiggleFrequency: 0.16,
            tumbleSpeed: 1.0,
            tumbleAmplitude: 9,
            tumbleFrequency: 0.18,
            tumbleTranslationMode: 'axis',
            tumbleAxisSource: 'assembly',
            tumbleAxis: 'z',
            audioWiggleSource: 'lowMids',
            audioWiggleStrength: 0.4,
            audioWiggleFloor: 0.02,
            audioTumbleSource: 'bass',
            audioTumbleStrength: 3.0,
            audioTumbleFloor: 0.14,
        }
    },
    {
        name: 'bass-spectrum',
        label: 'Bass + Spectrum',
        description: 'Strong bass translation combined with broad full-spectrum motion.',
        analysis: {
            wiggleEffectScale: 1.05,
            tumbleEffectScale: 1.2,
            fftSize: 1024,
            analysisSampleRate: 24000,
            bandNormalizationGain: 12,
            amplitudeAttackMs: 10,
            amplitudeReleaseMs: 160,
            bandAttackMs: 12,
            bandReleaseMs: 220,
            beatAttackMs: 0,
            beatReleaseMs: 190,
            dominantFrequencyAttackMs: 10,
            dominantFrequencyReleaseMs: 130,
            beatThreshold: 1.1,
            beatSensitivity: 12,
            beatBaselineMs: 210,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 7.2,
            wiggleAmplitude: 0.65,
            wiggleFrequency: 0.2,
            tumbleSpeed: 1.05,
            tumbleAmplitude: 8,
            tumbleFrequency: 0.18,
            tumbleTranslationMode: 'axis',
            tumbleAxisSource: 'assembly',
            tumbleAxis: 'z',
            audioWiggleSource: 'mix',
            audioWiggleStrength: 1.5,
            audioWiggleFloor: 0.06,
            audioTumbleSource: 'bass',
            audioTumbleStrength: 3.0,
            audioTumbleFloor: 0.12,
        }
    },
    {
        name: 'ambient-pulse',
        label: 'Ambient Pulse',
        description: 'Low continuous motion for slower or softer tracks.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 2048,
            analysisSampleRate: 22050,
            bandNormalizationGain: 8,
            amplitudeAttackMs: 25,
            amplitudeReleaseMs: 260,
            bandAttackMs: 30,
            bandReleaseMs: 320,
            beatAttackMs: 10,
            beatReleaseMs: 260,
            dominantFrequencyAttackMs: 30,
            dominantFrequencyReleaseMs: 220,
            beatThreshold: 1.25,
            beatSensitivity: 8,
            beatBaselineMs: 320,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 5,
            wiggleAmplitude: 0.6,
            wiggleFrequency: 0.16,
            tumbleSpeed: 0.8,
            tumbleAmplitude: 2.2,
            tumbleFrequency: 0.16,
            audioWiggleSource: 'mix',
            audioWiggleStrength: 1.0,
            audioWiggleFloor: 0.12,
            audioTumbleSource: 'amplitude',
            audioTumbleStrength: 1.4,
            audioTumbleFloor: 0.18,
        }
    },
    {
        name: 'performance',
        label: 'Performance',
        description: 'Lower-cost audio motion with tumble emphasized and wiggle mostly disabled.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 1024,
            analysisSampleRate: 22050,
            bandNormalizationGain: 9,
            amplitudeAttackMs: 15,
            amplitudeReleaseMs: 160,
            bandAttackMs: 20,
            bandReleaseMs: 220,
            beatAttackMs: 0,
            beatReleaseMs: 180,
            dominantFrequencyAttackMs: 15,
            dominantFrequencyReleaseMs: 140,
            beatThreshold: 1.16,
            beatSensitivity: 10,
            beatBaselineMs: 220,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 5,
            wiggleAmplitude: 0,
            wiggleFrequency: 0.16,
            tumbleSpeed: 0.95,
            tumbleAmplitude: 5.5,
            tumbleFrequency: 0.18,
            tumbleTranslationMode: 'axis',
            tumbleAxisSource: 'assembly',
            tumbleAxis: 'z',
            audioWiggleSource: 'off',
            audioWiggleStrength: 0,
            audioWiggleFloor: 0,
            audioTumbleSource: 'bass',
            audioTumbleStrength: 2.1,
            audioTumbleFloor: 0.08,
        }
    },
    {
        name: 'full-spectrum',
        label: 'Full Spectrum',
        description: 'Broad energy response with stronger mids and highs.',
        analysis: {
            wiggleEffectScale: 1,
            tumbleEffectScale: 1,
            fftSize: 1024,
            analysisSampleRate: 0,
            bandNormalizationGain: 11,
            amplitudeAttackMs: 10,
            amplitudeReleaseMs: 150,
            bandAttackMs: 12,
            bandReleaseMs: 200,
            beatAttackMs: 0,
            beatReleaseMs: 200,
            dominantFrequencyAttackMs: 10,
            dominantFrequencyReleaseMs: 120,
            beatThreshold: 1.12,
            beatSensitivity: 12,
            beatBaselineMs: 220,
        },
        animation: {
            wiggleMode: 'position',
            wiggleSpeed: 7.5,
            wiggleAmplitude: 0.8,
            wiggleFrequency: 0.22,
            tumbleSpeed: 1.1,
            tumbleAmplitude: 5,
            tumbleFrequency: 0.2,
            audioWiggleSource: 'mids',
            audioWiggleStrength: 1.4,
            audioWiggleFloor: 0.04,
            audioTumbleSource: 'mix',
            audioTumbleStrength: 1.7,
            audioTumbleFloor: 0.06,
        }
    },
] as const;

export function getAudioReactivePreset(name: AudioReactivePresetName) {
    const preset = AudioReactivePresetDefinitions.find(p => p.name === name);
    if (!preset) throw new Error(`Unknown audio reactive preset '${name}'.`);
    return preset;
}
